name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    env: 
      GO_VERSION: 1.22
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check and get dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...
